<a href="https://colab.research.google.com/github/izonejangwonyoung/tensorflow_lifecode/blob/master/Tensorflow_1_19_%ED%9E%88%EB%93%A0%EB%A0%88%EC%9D%B4%EC%96%B4_(%EC%8B%A4%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
#과거의 데이터를 준비합니다.
파일경로='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴=pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
#변수 분리
독립=보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax','ptratio', 'b', 'lstat']]
종속=보스턴[[ 'medv']]
print(독립.shape,종속.shape)

(506, 13) (506, 1)


In [ ]:
#모델의 구조를 만듭니다. 
X=tf.keras.layers.Input(shape=[13])
H=tf.keras.layers.Dense(10,activation='swish')(X)
Y=tf.keras.layers.Dense(1)(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='mse')


In [ ]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(독립,종속,epochs=1000,verbose=0)
model.fit(독립,종속,epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.1162
Epoch 2/10
16/16 [==============================] - 0s 894us/step - loss: 20.4917
Epoch 3/10
16/16 [==============================] - 0s 878us/step - loss: 22.0394
Epoch 4/10
16/16 [==============================] - 0s 905us/step - loss: 20.1460
Epoch 5/10
16/16 [==============================] - 0s 968us/step - loss: 23.3677
Epoch 6/10
16/16 [==============================] - 0s 956us/step - loss: 20.6681
Epoch 7/10
16/16 [==============================] - 0s 887us/step - loss: 23.6385
Epoch 8/10
16/16 [==============================] - 0s 958us/step - loss: 21.6476
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 20.6925
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 22.0751


**Tensorflow 1 - 17. 아이리스 품종 분류 (실습)**

In [ ]:
import tensorflow as tf
import pandas as pd
파일경로='https://raw.githubusercontent.com/izonejangwonyoung/tensorflow1/master/csv/iris.csv'
아이리스=pd.read_csv(파일경로)
아이리스.head()
#원핫인코딩
인코딩=pd.get_dummies(아이리스)
#독립변수와 종속변수
독립=인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속=인코딩[[ '품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


In [ ]:
X=tf.keras.layers.Input(shape=[4])
H=tf.keras.layers.Dense(5, activation="swish")(X)
H=tf.keras.layers.Dense(5, activation="swish")(H)
H=tf.keras.layers.Dense(5, activation="swish")(H)
Y=tf.keras.layers.Dense(3, activation='softmax')(X)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
model.fit(독립,종속,epochs=500)

In [ ]:
print(model.predict(독립[-5:]))
print(종속[-5:])

[[3.4243089e-07 7.4959867e-02 9.2503983e-01]
 [1.1941477e-06 1.4611486e-01 8.5388392e-01]
 [2.1703092e-06 2.0623343e-01 7.9376441e-01]
 [4.4980865e-07 1.1106341e-01 8.8893616e-01]
 [6.4058186e-06 3.4616932e-01 6.5382433e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
